INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Eraser Month', 'Stationery', 1924.87, true, 'http://images.com/Democrat.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Electric Kettle Number', 'Fitness', 892.97, true, 'http://images.com/partner.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Yoga Mat Class', 'Electronics', 1478.29, true, 'http://images.com/sense.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Hand Sanitizer Water', 'Books', 905.38, false, 'http://images.com/while.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Notebook Each', 'Fitness', 985.22, true, 'http://images.com/training.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Air Purifier Analysis', 'Toys', 1178.5, false, 'http://images.com/keep.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Whiteboard Morning', 'Furniture', 180.55, false, 'http://images.com/job.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Mechanical Pencil Matter', 'Fitness', 1125.41, false, 'http://images.com/agree.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Blender Anything', 'Kitchen', 58.04, false, 'http://images.com/good.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Desk Organizer Public', 'Books', 150.65, true, 'http://images.com/to.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Whiteboard Cut', 'Stationery', 231.87, true, 'http://images.com/simple.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('LED Strip Wide', 'Kitchen', 531.34, true, 'http://images.com/leader.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Blender Any', 'Kitchen', 805.9, true, 'http://images.com/whom.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Eraser Ten', 'Furniture', 789.49, false, 'http://images.com/maybe.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Yoga Mat They', 'Furniture', 2801.23, true, 'http://images.com/born.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Smartphone Stand Visit', 'Furniture', 819.7, false, 'http://images.com/training.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Wall Clock Down', 'Furniture', 2816.34, true, 'http://images.com/population.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Hand Sanitizer Grow', 'Books', 2208.08, true, 'http://images.com/season.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Blender Mother', 'Fitness', 1789.1, false, 'http://images.com/black.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Eraser Keep', 'Stationery', 640.57, false, 'http://images.com/language.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Desk Organizer Suggest', 'Books', 380.97, false, 'http://images.com/lay.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Headphones Debate', 'Stationery', 2590.57, true, 'http://images.com/will.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('LED Strip Hard', 'Stationery', 2642.55, true, 'http://images.com/trade.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Yoga Mat Past', 'Stationery', 1435.26, true, 'http://images.com/others.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Water Bottle Meet', 'Electronics', 983.29, true, 'http://images.com/decade.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Wall Clock Road', 'Toys', 2311.83, false, 'http://images.com/we.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Gaming Keyboard Herself', 'Books', 2826.98, false, 'http://images.com/trial.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Headphones His', 'Furniture', 2308.44, true, 'http://images.com/throughout.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('USB Cable Book', 'Stationery', 2662.7, true, 'http://images.com/cut.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Air Purifier Cost', 'Toys', 986.09, true, 'http://images.com/plan.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Hand Sanitizer View', 'Books', 1349.12, false, 'http://images.com/little.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Gaming Keyboard Recent', 'Fitness', 2924.49, true, 'http://images.com/edge.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Mechanical Pencil Own', 'Books', 169.82, false, 'http://images.com/rule.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Water Bottle Live', 'Furniture', 2887.81, true, 'http://images.com/evening.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Cutting Board Believe', 'Books', 2159.34, false, 'http://images.com/green.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Gaming Keyboard Him', 'Electronics', 499.12, true, 'http://images.com/after.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Notebook Future', 'Kitchen', 1758.31, true, 'http://images.com/wrong.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Mechanical Pencil Nor', 'Stationery', 1942.47, false, 'http://images.com/condition.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Cutting Board Draw', 'Electronics', 622.5, true, 'http://images.com/though.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Headphones Account', 'Fitness', 1787.54, true, 'http://images.com/different.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Blender Computer', 'Electronics', 476.28, false, 'http://images.com/her.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Cutting Board Get', 'Furniture', 1901.32, true, 'http://images.com/maybe.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Cutting Board Hospital', 'Kitchen', 373.07, true, 'http://images.com/forget.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Yoga Mat Choose', 'Books', 655.68, false, 'http://images.com/front.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Chair Mat Whether', 'Furniture', 1942.22, false, 'http://images.com/since.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Wall Clock Rest', 'Fitness', 1799.33, false, 'http://images.com/standard.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Smartphone Stand Bit', 'Books', 2585.47, false, 'http://images.com/situation.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Hand Sanitizer Consider', 'Fitness', 1154.67, false, 'http://images.com/trouble.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Notebook Budget', 'Kitchen', 411.18, true, 'http://images.com/record.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Smartphone Stand End', 'Electronics', 1796.25, true, 'http://images.com/study.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Air Purifier Power', 'Electronics', 2627.72, false, 'http://images.com/current.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Air Purifier Four', 'Stationery', 1402.71, true, 'http://images.com/top.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Hand Sanitizer Single', 'Furniture', 1537.27, false, 'http://images.com/everybody.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Eraser Ago', 'Stationery', 848.39, false, 'http://images.com/sense.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Eraser Situation', 'Electronics', 1858.74, false, 'http://images.com/north.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Headphones Line', 'Electronics', 1367.86, false, 'http://images.com/happen.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Stapler At', 'Electronics', 774.27, false, 'http://images.com/lay.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('USB Cable Well', 'Fitness', 1748.76, true, 'http://images.com/his.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Cutting Board Four', 'Fitness', 1347.45, false, 'http://images.com/throw.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Hand Sanitizer Camera', 'Fitness', 1623.97, true, 'http://images.com/speech.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Wall Clock Herself', 'Stationery', 226.99, true, 'http://images.com/herself.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Hand Sanitizer Quite', 'Stationery', 1503.07, true, 'http://images.com/until.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Whiteboard Build', 'Kitchen', 2987.01, false, 'http://images.com/mother.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Gaming Keyboard Sing', 'Kitchen', 2333.63, false, 'http://images.com/energy.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Electric Kettle Government', 'Books', 2346.6, false, 'http://images.com/single.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Mechanical Pencil Yeah', 'Fitness', 1608.36, false, 'http://images.com/wait.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Smartphone Stand Rich', 'Fitness', 59.04, true, 'http://images.com/trial.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('LED Strip Star', 'Kitchen', 1717.09, false, 'http://images.com/study.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Mechanical Pencil Few', 'Kitchen', 1894.62, true, 'http://images.com/decide.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('USB Cable Parent', 'Books', 604.34, false, 'http://images.com/well.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Stapler Rich', 'Toys', 530.1, true, 'http://images.com/support.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Yoga Mat Enough', 'Fitness', 417.63, false, 'http://images.com/free.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Whiteboard Drug', 'Furniture', 1798.78, true, 'http://images.com/kind.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Blender Prepare', 'Stationery', 1054.61, false, 'http://images.com/material.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Headphones Few', 'Books', 2285.54, true, 'http://images.com/ball.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Cutting Board See', 'Kitchen', 2303.06, true, 'http://images.com/gas.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Smartphone Stand During', 'Kitchen', 2035.62, false, 'http://images.com/word.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Blender Executive', 'Kitchen', 655.27, false, 'http://images.com/that.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Blender Mind', 'Books', 1834.11, false, 'http://images.com/under.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Mechanical Pencil Energy', 'Toys', 952.57, false, 'http://images.com/recent.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Wall Clock Culture', 'Toys', 2433.33, true, 'http://images.com/wide.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Smartphone Stand Knowledge', 'Furniture', 872.17, true, 'http://images.com/something.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Cutting Board Argue', 'Furniture', 2717.04, false, 'http://images.com/now.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Gaming Keyboard Seven', 'Electronics', 1434.22, false, 'http://images.com/kitchen.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Wall Clock Five', 'Furniture', 2355.35, true, 'http://images.com/item.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Air Purifier Teacher', 'Fitness', 2032.34, true, 'http://images.com/play.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Water Bottle Before', 'Toys', 2303.69, false, 'http://images.com/local.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Eraser Detail', 'Kitchen', 933.38, true, 'http://images.com/minute.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Water Bottle Assume', 'Toys', 1837.44, false, 'http://images.com/watch.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Whiteboard Music', 'Electronics', 1886.61, false, 'http://images.com/learn.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Desk Organizer Nothing', 'Electronics', 785.83, false, 'http://images.com/star.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Yoga Mat Religious', 'Books', 2002.92, true, 'http://images.com/radio.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Headphones Politics', 'Stationery', 682.3, true, 'http://images.com/million.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Eraser West', 'Toys', 2846.07, true, 'http://images.com/throughout.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Cutting Board Office', 'Kitchen', 1354.74, true, 'http://images.com/wish.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Stapler Maybe', 'Furniture', 409.38, false, 'http://images.com/suffer.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Electric Kettle Personal', 'Electronics', 319.07, true, 'http://images.com/affect.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Desk Organizer Tree', 'Kitchen', 2532.39, false, 'http://images.com/throughout.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Yoga Mat Another', 'Furniture', 271.12, false, 'http://images.com/memory.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Notebook Clear', 'Electronics', 1051.11, true, 'http://images.com/large.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Hand Sanitizer Family', 'Electronics', 1770.49, true, 'http://images.com/pretty.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Eraser Low', 'Furniture', 2343.57, true, 'http://images.com/would.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Air Purifier Congress', 'Toys', 688.88, true, 'http://images.com/mention.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('LED Strip Like', 'Electronics', 2980.76, false, 'http://images.com/paper.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Gaming Keyboard Full', 'Fitness', 1135.59, false, 'http://images.com/whether.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Stapler Until', 'Books', 2329.14, false, 'http://images.com/movie.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Hand Sanitizer Buy', 'Kitchen', 691.65, false, 'http://images.com/type.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Smartphone Stand Blood', 'Electronics', 294.67, true, 'http://images.com/see.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Stapler Front', 'Kitchen', 285.27, false, 'http://images.com/new.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Headphones Hotel', 'Furniture', 1103.07, false, 'http://images.com/recently.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Eraser Next', 'Fitness', 177.08, false, 'http://images.com/national.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Stapler Speak', 'Stationery', 2013.91, false, 'http://images.com/central.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Mechanical Pencil Amount', 'Stationery', 2810.78, true, 'http://images.com/light.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Eraser Much', 'Books', 116.87, false, 'http://images.com/property.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Cutting Board Increase', 'Kitchen', 2950.97, true, 'http://images.com/medical.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Cutting Board Produce', 'Furniture', 1608.48, false, 'http://images.com/stuff.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Hand Sanitizer Phone', 'Kitchen', 1998.85, false, 'http://images.com/difference.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Blender Summer', 'Toys', 396.05, false, 'http://images.com/and.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Notebook Tell', 'Furniture', 2237.16, false, 'http://images.com/design.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Desk Organizer Back', 'Electronics', 2207.7, true, 'http://images.com/near.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Desk Organizer Success', 'Fitness', 610.85, true, 'http://images.com/house.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Chair Mat Improve', 'Fitness', 760.47, true, 'http://images.com/what.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Yoga Mat Enough', 'Books', 2075.26, true, 'http://images.com/lose.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Notebook Manage', 'Fitness', 1596.57, false, 'http://images.com/build.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Gaming Keyboard Visit', 'Kitchen', 1802.76, true, 'http://images.com/main.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Stapler Visit', 'Kitchen', 2078.07, true, 'http://images.com/small.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Hand Sanitizer Big', 'Books', 922.11, false, 'http://images.com/successful.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Eraser Consumer', 'Books', 1341.85, true, 'http://images.com/center.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Eraser Even', 'Toys', 2025.69, true, 'http://images.com/care.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Hand Sanitizer Like', 'Toys', 2383.07, true, 'http://images.com/moment.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('USB Cable Part', 'Kitchen', 2155.96, false, 'http://images.com/agent.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Air Purifier Record', 'Furniture', 497.59, false, 'http://images.com/poor.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Notebook Hit', 'Fitness', 2208.12, false, 'http://images.com/country.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Notebook Poor', 'Stationery', 422.59, false, 'http://images.com/discuss.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Smartphone Stand Hold', 'Electronics', 2946.3, false, 'http://images.com/level.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Notebook From', 'Books', 359.52, true, 'http://images.com/list.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Whiteboard Nice', 'Electronics', 1316.2, true, 'http://images.com/us.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Blender Win', 'Toys', 1278.96, true, 'http://images.com/upon.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Stapler Central', 'Books', 2259.86, false, 'http://images.com/might.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Headphones Institution', 'Furniture', 68.5, false, 'http://images.com/situation.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Water Bottle Democrat', 'Furniture', 2580.92, false, 'http://images.com/ability.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Mechanical Pencil Hit', 'Kitchen', 1396.7, false, 'http://images.com/agency.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Cutting Board Fire', 'Fitness', 1680.53, true, 'http://images.com/authority.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Smartphone Stand Agent', 'Books', 2583.82, false, 'http://images.com/skill.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Cutting Board Tell', 'Fitness', 191.53, true, 'http://images.com/stop.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Cutting Board Eat', 'Fitness', 2000.81, true, 'http://images.com/economy.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Eraser Strong', 'Books', 164.28, false, 'http://images.com/project.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Hand Sanitizer Entire', 'Toys', 1660.79, true, 'http://images.com/throw.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Notebook Society', 'Stationery', 2496.15, false, 'http://images.com/wear.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Air Purifier Decide', 'Fitness', 1890.9, true, 'http://images.com/go.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Whiteboard Nation', 'Kitchen', 1692.28, true, 'http://images.com/skin.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Wall Clock Turn', 'Stationery', 1062.8, false, 'http://images.com/particular.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Chair Mat Result', 'Toys', 2938.36, false, 'http://images.com/art.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Water Bottle She', 'Fitness', 255.02, false, 'http://images.com/successful.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('LED Strip Final', 'Stationery', 758.95, false, 'http://images.com/west.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Notebook Eye', 'Furniture', 989.1, true, 'http://images.com/small.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Wall Clock Of', 'Toys', 969.95, false, 'http://images.com/couple.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Wall Clock Set', 'Stationery', 2107.1, false, 'http://images.com/pull.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('USB Cable Energy', 'Electronics', 1033.94, true, 'http://images.com/within.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Hand Sanitizer Professional', 'Furniture', 132.93, false, 'http://images.com/impact.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Water Bottle Improve', 'Furniture', 2811.22, false, 'http://images.com/everybody.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Smartphone Stand First', 'Toys', 1695.05, false, 'http://images.com/where.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Desk Organizer Become', 'Furniture', 2712.8, false, 'http://images.com/performance.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Wall Clock Claim', 'Stationery', 745.68, true, 'http://images.com/though.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Blender We', 'Books', 220.2, false, 'http://images.com/first.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Eraser Rule', 'Kitchen', 2391.83, false, 'http://images.com/front.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Electric Kettle Significant', 'Toys', 2502.08, true, 'http://images.com/cut.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Eraser Spend', 'Electronics', 2244.06, true, 'http://images.com/area.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('LED Strip Keep', 'Furniture', 1135.84, true, 'http://images.com/assume.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Whiteboard Unit', 'Electronics', 1075.66, false, 'http://images.com/loss.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Gaming Keyboard Amount', 'Fitness', 172.44, true, 'http://images.com/chance.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Blender Take', 'Furniture', 2719.24, true, 'http://images.com/mouth.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Stapler Idea', 'Stationery', 2297.1, false, 'http://images.com/buy.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Eraser Both', 'Electronics', 74.35, true, 'http://images.com/door.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Hand Sanitizer Amount', 'Electronics', 2373.96, true, 'http://images.com/responsibility.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Blender Any', 'Books', 201.95, false, 'http://images.com/drug.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Notebook Boy', 'Furniture', 445.78, false, 'http://images.com/question.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Whiteboard Remain', 'Stationery', 2339.56, false, 'http://images.com/must.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Air Purifier Far', 'Furniture', 189.65, true, 'http://images.com/behavior.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Eraser Already', 'Furniture', 169.7, false, 'http://images.com/green.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Hand Sanitizer In', 'Toys', 1221.1, false, 'http://images.com/fill.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Yoga Mat Last', 'Furniture', 1829.42, true, 'http://images.com/green.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Desk Organizer Sister', 'Electronics', 1480.73, false, 'http://images.com/its.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Desk Organizer Send', 'Furniture', 1949.01, false, 'http://images.com/writer.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Water Bottle Speech', 'Electronics', 854.29, true, 'http://images.com/surface.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Notebook Remember', 'Furniture', 1062.03, true, 'http://images.com/off.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Chair Mat Coach', 'Fitness', 2651.01, true, 'http://images.com/crime.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Headphones Spring', 'Electronics', 204.82, true, 'http://images.com/leader.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Mechanical Pencil Walk', 'Electronics', 2518.85, false, 'http://images.com/research.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Cutting Board Expert', 'Books', 370.41, false, 'http://images.com/hear.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('USB Cable Character', 'Fitness', 2868.18, false, 'http://images.com/another.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Yoga Mat Choice', 'Electronics', 2653.5, false, 'http://images.com/west.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Gaming Keyboard Mention', 'Toys', 913.71, true, 'http://images.com/discuss.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Smartphone Stand Them', 'Fitness', 69.0, true, 'http://images.com/join.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Hand Sanitizer Operation', 'Furniture', 1703.27, false, 'http://images.com/assume.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Headphones Whom', 'Kitchen', 1539.53, true, 'http://images.com/where.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Electric Kettle Law', 'Stationery', 875.48, false, 'http://images.com/serious.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Stapler Design', 'Furniture', 1288.94, false, 'http://images.com/investment.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Chair Mat Spring', 'Electronics', 2409.34, false, 'http://images.com/night.png');
INSERT INTO products (product_name, category, price, featured, image_url) VALUES ('Whiteboard Field', 'Fitness', 470.37, false, 'http://images.com/blood.png');